package com.crimsonlogic.ecommerce.service.impl;

import com.crimsonlogic.ecommerce.dao.CustomerMapper;
import com.crimsonlogic.ecommerce.exception.DuplicateUserException;
import com.crimsonlogic.ecommerce.exception.ValidationException;
import com.crimsonlogic.ecommerce.model.Address;
import com.crimsonlogic.ecommerce.model.Customer;
import com.crimsonlogic.ecommerce.service.CustomerService;
import com.crimsonlogic.ecommerce.service.abstraction.UserService;
import com.crimsonlogic.ecommerce.util.IdGenerator;
import com.crimsonlogic.ecommerce.util.ValidationUtil;

import java.util.List;

/**
 * Customer service implementation.
 *
 * Contains all Customer business logic and validation.
 *
 * Rules:
 * - Validation is handled in service layer.
 * - Customer IDs are generated in service layer.
 * - Duplicate email/phone checks are handled here.
 * - Controllers must not contain Customer business logic.
 * - CartItem is NOT used anywhere. The project uses Cart.
 */
public class CustomerServiceImpl
        extends UserService<Customer>
        implements CustomerService {

    private CustomerMapper customerMapper;


    // ==========================================================
    // SETTER
    // ==========================================================

    /**
     * Sets CustomerMapper.
     *
     * @param customerMapper CustomerMapper
     */
    public void setCustomerMapper(
            CustomerMapper customerMapper) {

        this.customerMapper = customerMapper;
    }


    // ==========================================================
    // CUSTOMER REGISTRATION / INSERT
    // ==========================================================

    /**
     * Inserts a Customer.
     *
     * This method is kept for compatibility with the existing
     * project architecture.
     *
     * Customer registration through AuthenticationService already
     * performs:
     * - validation
     * - duplicate checks
     * - ID generation
     * - password encryption
     *
     * Therefore this method does not encrypt the password again.
     *
     * @param customer Customer
     */
    @Override
    public void insertCustomer(
            Customer customer) {

        if (customer == null) {

            throw new ValidationException(
                    "Customer information is required.");
        }


        /*
         * Validate common customer information.
         */
        validateCommonProfile(customer);


        /*
         * Generate Customer ID only when it has not already
         * been generated by AuthenticationService.
         *
         * ID generation remains inside the service layer.
         */
        if (customer.getUserId() == null ||
                customer.getUserId().trim().isEmpty()) {

            customer.setUserId(
                    IdGenerator.generateId("CUS"));
        }


        /*
         * Normalize values before persistence.
         */
        customer.setUserName(
                customer.getUserName().trim());

        customer.setUserEmail(
                customer.getUserEmail().trim());

        customer.setUserPhNo(
                customer.getUserPhNo().trim());


        /*
         * Check duplicate email.
         */
        Customer existingEmailCustomer =
                customerMapper.findCustomerByEmail(
                        customer.getUserEmail());

        if (existingEmailCustomer != null) {

            throw new DuplicateUserException(
                    "Email is already registered.");
        }


        /*
         * Check duplicate phone.
         */
        Customer existingPhoneCustomer =
                customerMapper.findCustomerByPhone(
                        customer.getUserPhNo());

        if (existingPhoneCustomer != null) {

            throw new DuplicateUserException(
                    "Phone number is already registered.");
        }


        /*
         * Insert Customer.
         */
        customerMapper.insertCustomer(customer);
    }


    // ==========================================================
    // UPDATE CUSTOMER PROFILE
    // ==========================================================

    /**
     * Updates Customer profile.
     *
     * Customer is allowed to update:
     * - Name
     * - Email
     * - Phone
     *
     * Password is NOT updated through this method.
     * Password changes must use changePassword().
     *
     * @param customer Customer
     */
    @Override
    public void updateCustomer(
            Customer customer) {

        if (customer == null) {

            throw new ValidationException(
                    "Customer information is required.");
        }


        /*
         * Customer ID is mandatory.
         */
        validateCustomerId(
                customer.getUserId());


        /*
         * Validate name, email and phone.
         */
        validateCommonProfile(customer);


        /*
         * Fetch existing customer.
         */
        Customer existingCustomer =
                customerMapper.findCustomerById(
                        customer.getUserId());

        if (existingCustomer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        /*
         * Normalize input.
         */
        customer.setUserName(
                customer.getUserName().trim());

        customer.setUserEmail(
                customer.getUserEmail().trim());

        customer.setUserPhNo(
                customer.getUserPhNo().trim());


        /*
         * Check duplicate email.
         *
         * The customer's own existing email is allowed.
         */
        Customer emailCustomer =
                customerMapper.findCustomerByEmail(
                        customer.getUserEmail());

        if (emailCustomer != null &&
                !customer.getUserId().equals(
                        emailCustomer.getUserId())) {

            throw new DuplicateUserException(
                    "Email is already registered by another user.");
        }


        /*
         * Check duplicate phone.
         *
         * The customer's own existing phone is allowed.
         */
        Customer phoneCustomer =
                customerMapper.findCustomerByPhone(
                        customer.getUserPhNo());

        if (phoneCustomer != null &&
                !customer.getUserId().equals(
                        phoneCustomer.getUserId())) {

            throw new DuplicateUserException(
                    "Phone number is already registered by another user.");
        }


        /*
         * Password must never come from the profile form.
         *
         * Preserve the existing encrypted password.
         */
        customer.setUserPassword(
                existingCustomer.getUserPassword());


        /*
         * Wallet balance must not be modified through
         * customer profile update.
         */
        customer.setWalletBalance(
                existingCustomer.getWalletBalance());


        /*
         * Persist only the allowed profile fields.
         *
         * CustomerMapper.xml will update:
         * - user_name
         * - user_email
         * - user_phone
         *
         * It must NOT update user_password here.
         */
        customerMapper.updateCustomer(customer);
    }


    // ==========================================================
    // UPDATE PASSWORD
    // ==========================================================

    /**
     * Updates an already encrypted Customer password.
     *
     * Password validation and encryption are handled by
     * changePassword().
     *
     * @param userId Customer ID
     * @param userPassword Encrypted password
     */
    @Override
    public void updatePassword(
            String userId,
            String userPassword) {

        validateCustomerId(userId);


        if (userPassword == null ||
                userPassword.trim().isEmpty()) {

            throw new ValidationException(
                    "Password is required.");
        }


        /*
         * Customer must exist.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        userId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        customerMapper.updatePassword(
                userId,
                userPassword);
    }


    // ==========================================================
    // DELETE CUSTOMER
    // ==========================================================

    /**
     * Deletes a Customer.
     *
     * All deletion-related business validation belongs here.
     *
     * The database cleanup implementation will be handled through
     * CustomerMapper in the next file.
     *
     * @param customerId Customer ID
     */
    @Override
    public void deleteCustomer(
            String customerId) {

        /*
         * Validate Customer ID.
         */
        validateCustomerId(customerId);


        /*
         * Verify that the Customer exists.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        customerId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        /*
         * Delete through DAO.
         *
         * Controller does not directly access mapper.
         */
        customerMapper.deleteCustomer(
                customerId);
    }


    // ==========================================================
    // FIND CUSTOMER BY ID
    // ==========================================================

    /**
     * Finds Customer by ID.
     *
     * @param customerId Customer ID
     * @return Customer
     */
    @Override
    public Customer findCustomerById(
            String customerId) {

        validateCustomerId(customerId);

        return customerMapper.findCustomerById(
                customerId.trim());
    }


    // ==========================================================
    // FIND CUSTOMER BY EMAIL
    // ==========================================================

    /**
     * Finds Customer by email.
     *
     * @param email Email
     * @return Customer
     */
    @Override
    public Customer findCustomerByEmail(
            String email) {

        if (email == null ||
                email.trim().isEmpty()) {

            throw new ValidationException(
                    "Email is required.");
        }


        ValidationUtil.validateEmail(
                email.trim());


        return customerMapper.findCustomerByEmail(
                email.trim());
    }


    // ==========================================================
    // FIND CUSTOMER BY PHONE
    // ==========================================================

    /**
     * Finds Customer by phone.
     *
     * @param phone Phone number
     * @return Customer
     */
    @Override
    public Customer findCustomerByPhone(
            String phone) {

        if (phone == null ||
                phone.trim().isEmpty()) {

            throw new ValidationException(
                    "Phone number is required.");
        }


        ValidationUtil.validatePhone(
                phone.trim());


        return customerMapper.findCustomerByPhone(
                phone.trim());
    }


    // ==========================================================
    // FIND ALL CUSTOMERS
    // ==========================================================

    /**
     * Returns all Customers.
     *
     * @return Customer list
     */
    @Override
    public List<Customer> findAllCustomers() {

        return customerMapper.findAllCustomers();
    }


    // ==========================================================
    // UPDATE WALLET BALANCE
    // ==========================================================

    /**
     * Updates Customer wallet balance.
     *
     * Wallet balance cannot be negative.
     *
     * @param customerId Customer ID
     * @param walletBalance Wallet balance
     */
    @Override
    public void updateWalletBalance(
            String customerId,
            double walletBalance) {

        validateCustomerId(customerId);


        if (walletBalance < 0) {

            throw new ValidationException(
                    "Wallet balance cannot be negative.");
        }


        /*
         * Verify Customer exists.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        customerId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        customerMapper.updateWalletBalance(
                customerId,
                walletBalance);
    }


    // ==========================================================
    // CHANGE PASSWORD
    // ==========================================================

    /**
     * Changes Customer password.
     *
     * Business rules:
     * - Customer must exist.
     * - Current password must be correct.
     * - New password must satisfy validation rules.
     * - Confirm password must match.
     * - New password cannot be same as current password.
     *
     * @param customerId Customer ID
     * @param currentPassword Current password
     * @param newPassword New password
     * @param confirmPassword Confirmation password
     */
    @Override
    public void changePassword(
            String customerId,
            String currentPassword,
            String newPassword,
            String confirmPassword) {

        validateCustomerId(customerId);


        /*
         * Find Customer.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        customerId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        /*
         * Reuse common UserService password business logic.
         *
         * This validates:
         * - current password
         * - new password
         * - confirmation password
         * - same-password restriction
         *
         * It also returns the newly encrypted password.
         */
        String encryptedPassword =
                generateNewPassword(
                        customer,
                        currentPassword,
                        newPassword,
                        confirmPassword);


        /*
         * Persist encrypted password.
         */
        customerMapper.updatePassword(
                customerId,
                encryptedPassword);
    }


    // ==========================================================
    // CUSTOMER ↔ ADDRESS
    // ==========================================================

    /**
     * Assigns an existing Address to Customer.
     *
     * @param customerId Customer ID
     * @param addressId Address ID
     */
    @Override
    public void assignAddress(
            String customerId,
            String addressId) {

        validateCustomerId(customerId);

        validateAddressId(addressId);


        /*
         * Customer must exist.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        customerId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        /*
         * Prevent duplicate customer-address assignment.
         */
        List<Address> addresses =
                customerMapper.findAddressesByCustomer(
                        customerId);

        if (addresses != null) {

            for (Address address : addresses) {

                if (addressId.equals(
                        address.getAddressId())) {

                    throw new ValidationException(
                            "Address is already assigned to this customer.");
                }
            }
        }


        customerMapper.assignAddressToCustomer(
                customerId,
                addressId);
    }


    /**
     * Removes an Address from Customer.
     *
     * @param customerId Customer ID
     * @param addressId Address ID
     */
    @Override
    public void removeAddress(
            String customerId,
            String addressId) {

        validateCustomerId(customerId);

        validateAddressId(addressId);


        /*
         * Customer must exist.
         */
        Customer customer =
                customerMapper.findCustomerById(
                        customerId);

        if (customer == null) {

            throw new ValidationException(
                    "Customer not found.");
        }


        /*
         * Verify that the address is actually assigned
         * to this customer.
         */
        List<Address> addresses =
                customerMapper.findAddressesByCustomer(
                        customerId);

        boolean addressAssigned = false;


        if (addresses != null) {

            for (Address address : addresses) {

                if (addressId.equals(
                        address.getAddressId())) {

                    addressAssigned = true;
                    break;
                }
            }
        }


        if (!addressAssigned) {

            throw new ValidationException(
                    "Address is not assigned to this customer.");
        }


        customerMapper.removeAddressFromCustomer(
                customerId,
                addressId);
    }


    /**
     * Finds all addresses assigned to Customer.
     *
     * @param customerId Customer ID
     * @return Address list
     */
    @Override
    public List<Address> findCustomerAddresses(
            String customerId) {

        validateCustomerId(customerId);

        return customerMapper.findAddressesByCustomer(
                customerId.trim());
    }


    // ==========================================================
    // VALIDATION HELPERS
    // ==========================================================

    /**
     * Validates Customer ID.
     *
     * @param customerId Customer ID
     */
    private void validateCustomerId(
            String customerId) {

        if (customerId == null ||
                customerId.trim().isEmpty()) {

            throw new ValidationException(
                    "Customer ID is required.");
        }
    }


    /**
     * Validates Address ID.
     *
     * @param addressId Address ID
     */
    private void validateAddressId(
            String addressId) {

        if (addressId == null ||
                addressId.trim().isEmpty()) {

            throw new ValidationException(
                    "Address ID is required.");
        }
    }


    @Override
    public void rechargeWallet(
            String customerId,
            double amount,
            String paymentMethod,
            String upiId) {


        // =====================================================
        // CUSTOMER VALIDATION
        // =====================================================

        if (customerId == null ||
                customerId.trim().isEmpty()) {

            throw new ValidationException(
                    "Customer ID is required."
            );
        }


        // =====================================================
        // AMOUNT VALIDATION
        // =====================================================

        if (amount <= 0) {

            throw new ValidationException(
                    "Recharge amount must be greater than zero."
            );
        }


        // =====================================================
        // PAYMENT METHOD VALIDATION
        // =====================================================

        if (paymentMethod == null ||
                paymentMethod.trim().isEmpty()) {

            throw new ValidationException(
                    "Payment method is required."
            );
        }


        // =====================================================
        // UPI PAYMENT
        // =====================================================

        if ("UPI".equals(paymentMethod)) {


            /*
             * Use the project's existing ValidationUtil.
             *
             * DO NOT duplicate the UPI regular expression here.
             */
            ValidationUtil.validateUpiId(
                    upiId
            );


            // -------------------------------------------------
            // FIND CUSTOMER
            // -------------------------------------------------

            Customer customer =
                    customerMapper.findCustomerById(
                            customerId
                    );


            if (customer == null) {

                throw new ValidationException(
                        "Customer not found."
                );
            }


            // -------------------------------------------------
            // CALCULATE NEW BALANCE
            // -------------------------------------------------

            double currentBalance =
                    customer.getWalletBalance();


            double newBalance =
                    currentBalance + amount;


            // -------------------------------------------------
            // UPDATE WALLET
            // -------------------------------------------------

            customerMapper.updateWalletBalance(
                    customerId,
                    newBalance
            );


            return;
        }


        // =====================================================
        // DEBIT CARD
        // =====================================================

        if ("DEBIT_CARD".equals(paymentMethod)) {

            /*
             * Debit Card is intentionally NOT implemented yet.
             *
             * We will add proper:
             * - card number validation
             * - expiry validation
             * - CVV validation
             * - payment processing
             *
             * later.
             *
             * Therefore NO WALLET UPDATE is performed here.
             */

            throw new ValidationException(
                    "Debit Card recharge is currently unavailable. "
                            + "Card validation will be implemented later."
            );
        }


        // =====================================================
        // INVALID PAYMENT METHOD
        // =====================================================

        throw new ValidationException(
                "Invalid payment method."
        );
    }
}